sudo: required

services:
  - docker

language: scala

scala:
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        make native-all && ./sbt "; test; publish";
      else
        make linux64 && ./sbt test;
      fi;
    else
      ./sbt test;
    fi
