branches:
  only:
  - master

language: scala

scala:
  - 2.12.11

matrix:
  include:
    - os: linux
      arch: s390x
      dist: xenial

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ "$TRAVIS_ARCH" = "s390x" ]; then
        sudo apt-get install -y openjdk-11-jdk;
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-s390x && export PATH=$JAVA_HOME/bin:$PATH;
      fi;
    fi

script:
  - ./script/travis-deploy.sh
